version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./inc/default.conf:/etc/nginx/conf.d/default.conf"
      - "./openrsc_web:/var/www/html/openrsc_web"
      - "./avatars:/var/www/html/openrsc_web/public/img/avatars"
      - "./board:/var/www/html/openrsc_web/public/board"
      - "./downloads:/var/www/html/openrsc_web/public/downloads"
      - "./cache:/var/www/html/openrsc_web/public/cache"
#      - "./etc/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
#      - "./etc/nginx/ssl:/etc/nginx/ssl"
#      - "./etc/nginx/log:/var/log/nginx"
      - "./wiki:/var/www/html/wiki"
#      - "./site/public/stylesheets:/var/www/html/site/public/stylesheets"
#      - "./site/public/images:/var/www/html/site/public/images"

  php:
    image: openrsc/php-laravel:latest
    container_name: php
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "./inc/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./openrsc_web:/var/www/html/openrsc_web"
      - "./board:/var/www/html/openrsc_web/public/board"
      - "./sql:/var/www/html/openrsc_web/public/sql"
      - "./downloads:/var/www/html/openrsc_web/public/downloads"

  mediawiki: # Optional, comment this section out if unwanted.
    image: mediawiki:latest
    container_name: mediawiki
    restart: always
    ports:
      - "127.0.0.1:9001:80"
    volumes:
      - "./etc/wiki/LocalSettings.php:/var/www/html/LocalSettings.php" # MediaWiki config is located in etc
      - "./wiki/images:/var/www/html/images"
      - "./wiki:/var/www/html"

  phpmyadmin: # Optional, comment this section out if unwanted.
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - HIDE_PHP_VERSION=true
      - UPLOAD_LIMIT=10485760
      - PMA_HOST=mariadb
    ports:
      - "4000:80"
    volumes:
      - "./etc/phpmyadmin/config.inc.php:/var/www/html/config.inc.php" # PHPMyAdmin config is located in etc

networks: # Required for connectivity with seperate docker-compose web framework
  default:
    external:
      name: database
