version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./portal:/var/www/html/portal"
      - "./avatars:/var/www/html/portal/public/img/avatars"
      - "./board:/var/www/html/portal/public/board"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro" # Nginx config is located in etc
      - "./etc/nginx/sites-available:/etc/nginx/sites-available:ro" # Nginx config is located in etc
      - "./etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro" # Nginx config is located in etc
      - "./etc/nginx/conf.d:/etc/nginx/conf.d:ro" # Nginx config is located in etc
      - "./etc/nginx/log:/var/log/nginx"
      - "./etc/nginx/ssl:/etc/nginx/ssl" # Cloudflare origin SSL cert path
      - "./wiki:/var/www/html/portal/public/wiki"
      - "./wiki/images:/var/www/html/portal/public/wiki/images"
      - "./wiki/skins:/var/www/html/portal/public/skins"
      - "./etc/wiki/LocalSettings.php:/var/www/html/portal/public/wiki/LocalSettings.php:ro" # MediaWiki config is located in etc
      - "./rsc-client/dist:/var/www/html/portal/public/client"

  php:
    build:
      context: "./etc/php"
      dockerfile: Dockerfile
      args:
        buildno: 1
#    image: openrsc/php-laravel:latest
    container_name: php
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
      - "1337:1337"
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro" # PHP config is located in etc
      - "./portal:/var/www/html/portal"
      - "./board:/var/www/html/portal/public/board"
      - "./wiki:/var/www/html/portal/public/wiki"
      - "./etc/wiki/LocalSettings.php:/var/www/html/portal/public/wiki/LocalSettings.php:ro" # MediaWiki config is located in etc

networks: # Required for connectivity with separate docker-compose web framework
  default:
    external:
      name: database
