version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./portal:/var/www/html/portal"
      - "./avatars:/var/www/html/portal/www/images/avatars"
      - "./board:/var/www/html/portal/www/board"
      - "./downloads:/var/www/html/portal/www/downloads"
      - "./etc/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./etc/nginx/ssl:/etc/nginx/ssl"
      - "./etc/nginx/log:/var/log/nginx"
      - "./wiki:/var/www/html/portal/www/wiki"
#      - "./site/www/stylesheets:/var/www/html/site/www/stylesheets"
#      - "./site/www/images:/var/www/html/site/www/images"

  php:
    image: openrsc/php-laravel:latest
    container_name: php
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "./etc/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./portal:/var/www/html/portal"
      - "./board:/var/www/html/portal/www/board"

  mediawiki: # Optional, comment this section out if unwanted.
    image: mediawiki:latest
    container_name: mediawiki
    restart: always
    volumes:
      - "./etc/wiki/LocalSettings.php:/var/www/html/LocalSettings.php" # MediaWiki config is located in etc
      - "./wiki/images:/var/www/html/images"
      - "./wiki:/var/www/html"

  phpmyadmin: # Optional, comment this section out if unwanted.
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - HIDE_PHP_VERSION=true
      - UPLOAD_LIMIT=10485760
      - PMA_HOST=mariadb
    volumes:
      - "./etc/phpmyadmin/config.inc.php:/var/www/html/config.inc.php" # PHPMyAdmin config is located in etc

networks: # Required for connectivity with seperate docker-compose web framework
  default:
    external:
      name: database
