<?php

return [
    'stats_page_generates_csv' => env('STATS_PAGE_GENERATES_CSV', false),
    'stats_hourly_job_enabled' => env('STATS_HOURLY_CSV_JOB_ENABLED', false),
    'stats_hourly_csv_job_enabled' => env('STATS_HOURLY_JOB_ENABLED', false),
    'stats_daily_job_enabled' => env('STATS_DAILY_CSV_JOB_ENABLED', false),
    'stats_daily_csv_job_enabled' => env('STATS_DAILY_JOB_ENABLED', false),
    'stats_weekly_job_enabled' => env('STATS_WEEKLY_CSV_JOB_ENABLED', false),
    'stats_weekly_csv_job_enabled' => env('STATS_WEEKLY_JOB_ENABLED', false),
    'stats_page_enabled' => env('STATS_PAGE_ENABLED', true),
    'force_https' => env('FORCE_HTTPS', false),
    'gpg_private_key_file' => env('GPG_PRIVATE_KEY_FILE', ''),
    'gpg_public_key_file' => env('GPG_PUBLIC_KEY_FILE', ''),
    'player_exports_enabled' => env('PLAYER_EXPORTS_ENABLED', false),
    'player_exports_api_enabled' => env('PLAYER_EXPORTS_API_ENABLED', false),
    'player_exports_admin_only' => env('PLAYER_EXPORTS_ADMIN_ONLY', false),
    'player_exports_moderator_only' => env('PLAYER_EXPORTS_MODERATOR_ONLY', false),
    'login_enabled' => env('LOGIN_ENABLED', true),
    'login_admin_only' => env('LOGIN_ADMIN_ONLY', false),
    'login_logging_enabled' => env('LOGIN_LOGGING_ENABLED', false),
    'board_enabled' => env('BOARD_ENABLED', true),
    'web_registration_enabled' => env('WEB_REGISTRATION_ENABLED', false),
    'api_registration_enabled' => env('API_REGISTRATION_ENABLED', false),
    'max_new_accounts_per_24_hours_preservation' => env('MAX_NEW_ACCOUNTS_PER_24_HOURS_PRESERVATION', 3),
    'max_new_accounts_per_24_hours_cabbage' => env('MAX_NEW_ACCOUNTS_PER_24_HOURS_CABBAGE', 3),
    'max_new_accounts_per_24_hours_2001scape' => env('MAX_NEW_ACCOUNTS_PER_24_HOURS_2001SCAPE', 2),
    'max_new_accounts_per_24_hours_openpk' => env('MAX_NEW_ACCOUNTS_PER_24_HOURS_OPENPK', 3),
    'max_new_accounts_per_24_hours_uranium' => env('MAX_NEW_ACCOUNTS_PER_24_HOURS_URANIUM', 10),
    'max_new_accounts_per_24_hours_coleslaw' => env('MAX_NEW_ACCOUNTS_PER_24_HOURS_COLESLAW', 20),
    'npc_hiscores_enabled' => env('NPC_HISCORES_ENABLED', false),
    'npc_overall_hiscores_enabled' => env('NPC_OVERALL_HISCORES_ENABLED', true),
    'npc_odyssey_hiscores_enabled' => env('NPC_ODYSSEY_HISCORES_ENABLED', true),
    'discord_url' => env('DISCORD_URL', 'https://discord.gg/ABdFCqn'),
    'discord_url_on_maintenance_page' => env('DISCORD_URL_ON_MAINTENANCE_PAGE', false),
    'caching_databases' => env('CACHING_DATABASES', false),
    'multi_world_logins' => env('MULTI_WORLD_LOGINS', true),
    'message_center_enabled' => env('MESSAGE_CENTER_ENABLED', true),
    'message_center_appeal_message_enabled' => env('MESSAGE_CENTER_APPEAL_MESSAGE_ENABLED', true),
    'password_resets_enabled' => env('PASSWORD_RESETS_ENABLED', false),
    'password_resets_discord_notifications' => env('PASSWORD_RESETS_DISCORD_NOTIFICATIONS', false),
    'password_resets_discord_webhook_url' => env('PASSWORD_RESETS_DISCORD_WEBHOOK_URL', ''),
    'max_password_resets_per_24_hours' => env('MAX_PASSWORD_RESETS_PER_24_HOURS', 3),
];
