package mudclient;

class BZState {
   final int j = 4096;
   final int k = 16;
   final int l = 258;
   final int m = 23;
   final int n = 0;
   final int o = 1;
   final int p = 6;
   final int q = 50;
   final int r = 4;
   final int s = 18002;
   byte[] t;
   int u;
   int v;
   int w;
   int x;
   byte[] y;
   int z;
   int ab;
   int bb;
   int cb;
   byte db;
   int eb;
   boolean fb;
   int gb;
   int hb;
   int ib;
   int jb;
   int kb;
   int lb;
   int mb;
   int[] nb = new int[256];
   int ob;
   int[] pb = new int[257];
   int[] qb = new int[257];
   public static int[] rb;
   int sb;
   boolean[] tb = new boolean[256];
   boolean[] ub = new boolean[16];
   byte[] vb = new byte[256];
   byte[] wb = new byte[4096];
   int[] xb = new int[16];
   byte[] yb = new byte[18002];
   byte[] zb = new byte[18002];
   byte[][] ac = new byte[6][258];
   int[][] bc = new int[6][258];
   int[][] cc = new int[6][258];
   int[][] dc = new int[6][258];
   int[] ec = new int[6];
   int fc;
}
